x-logging: &logging
  options:
    max-size: "256k"
    max-file: "1"
  driver: json-file

services:
  reverse-proxy:
    restart: always
    build:
      context: ./services/reverse-proxy
    ports:
      - "${LISTEN_IP}:80:80"
    environment:
      - API_BASE_URI=$API_BASE_URI
    logging: *logging

  gradio:
    build:
      context: ./services/gradio
      network: host
    restart: always
    logging: *logging
    networks:
      default:
        ipv4_address: "${STATIC_SUBNET}.101"
    environment:
      - WHISPER_BASE_URL=$WHISPER_BASE_URL
      - API_BASE_URI=$API_BASE_URI
      - OPENAI_BASE_URL=$OPENAI_BASE_URL
      - OPENAI_API_BASE=$OPENAI_API_BASE
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - LLM_TEXT_MODEL=$LLM_TEXT_MODEL
      - LLM_IMG_MODEL=$LLM_IMG_MODEL

  # backend:
  #   build:
  #     context: ./services/backend
  #     network: host
  #   restart: always
  #   environment:
  #     - "POSTGRES_HOST=postgres"
  #     - "POSTGRES_PASSWORD=$POSTGRES_PASSWORD"
  #     - "POSTGRES_USER=$POSTGRES_USER"
  #     - "POSTGRES_DB=$POSTGRES_DB"
  #   logging: *logging
  #   networks:
  #     default:
  #       ipv4_address: "${STATIC_SUBNET}.102"

  # postgres:
  #   build:
  #     context: ./services/postgres
  #   restart: always
  #   environment:
  #     - "POSTGRES_PASSWORD=$POSTGRES_PASSWORD"
  #     - "POSTGRES_USER=$POSTGRES_USER"
  #     - "POSTGRES_DB=$POSTGRES_DB"
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   logging: *logging

  # migrations:
  #   build:
  #     context: ./services/migrations
  #   restart: "no"
  #   environment:
  #     - DATABASE_URL=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB?sslmode=disable
  #   logging: *logging

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: "${STATIC_SUBNET}.0/24"
          gateway: "${STATIC_SUBNET}.1"

volumes:
  postgres-data:
