FROM python:3.12.3

WORKDIR /app

COPY ./requirements.txt ./requirements.txt
RUN echo "\ndebugpy==1.8.2\n" >> ./requirements.txt

RUN --mount=type=cache,mode=0755,target=/root/.cache \
  pip install -r requirements.txt

CMD ["python", "-Xfrozen_modules=off", "-m", "debugpy", "--listen", "0.0.0.0:5678", "-m", "uvicorn", "src.main:app", "--reload", "--host", "0.0.0.0", "--port", "3000"]
